SHOW USER;

SELECT username FROM dba_users WHERE username = 'PROJECT_USER';

CREATE USER project_user IDENTIFIED BY Project123;

GRANT CONNECT, RESOURCE TO project_user;

GRANT CREATE VIEW TO project_user;

GRANT CREATE PROCEDURE TO project_user;

GRANT CREATE TRIGGER TO project_user;

ALTER USER project_user QUOTA UNLIMITED ON USERS;

SHOW USER;

-- Table Clients
CREATE TABLE clients (
    client_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) UNIQUE NOT NULL,
    created_at DATE DEFAULT SYSDATE
);

-- Table Produits
CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(100) NOT NULL,
    price NUMBER(10,2) CHECK (price > 0),
    stock NUMBER DEFAULT 0 CHECK (stock >= 0)
);

-- Table Commandes
CREATE TABLE orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id NUMBER NOT NULL,
    order_date DATE DEFAULT SYSDATE,
    status VARCHAR2(30) DEFAULT 'PENDING',
    CONSTRAINT fk_client
        FOREIGN KEY (client_id)
        REFERENCES clients(client_id)
);

-- Table Lignes de commande
CREATE TABLE order_items (
    order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER,
    product_id NUMBER,
    quantity NUMBER CHECK (quantity > 0),
    CONSTRAINT fk_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id),
    CONSTRAINT fk_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
);

SELECT table_name 
FROM user_tables;


SHOW USER;

--- Insértion des clients

INSERT INTO clients (name, email)
VALUES ('Alice Martin', 'alice@email.com');

INSERT INTO clients (name, email)
VALUES ('Karim Benali', 'karim@email.com');

COMMIT;

--- Insértion des produits

INSERT INTO products (product_name, price, stock)
VALUES ('Laptop', 1200, 10);

INSERT INTO products (product_name, price, stock)
VALUES ('Mouse', 25, 100);

INSERT INTO products (product_name, price, stock)
VALUES ('Keyboard', 80, 50);

COMMIT;

--- vérification des données

SELECT* FROM clients;
SELECT* FROM products;

---Creation des procédures PL/SQL
CREATE OR REPLACE PROCEDURE create_order (
p_client_id IN NUMBER,
p_product_id IN NUMBER,
P_quantity IN NUMBER
) AS
v_stock NUMBER;
v_order_id NUMBER;

BEGIN 

---vérifier le stock disponible
SELECT stock INTO v_stock
FROM products
WHERE product_id = p_product_id
FOR UPDATE;


IF v_stock < p_quantity THEN
RAISE_APPLICATION_ERROR(-20001, 'Stock insufisant');
END IF;

---Créer la commande
INSERT INTO orders(client_id)
VALUES (p_client_id)
RETURNING order_id INTO v_order_id;

---Ajouter la ligne de commande
INSERT INTO order_items (order_id, product_id, quantity)
VALUES (v_order_id, p_product_id, p_quantity);

    COMMIT;
END;
/


--- test de la procédure

BEGIN
     create_order(1, 1, 2);
END;
/

--- Vérification

SELECT* FROM orders;
SELECT* FROM order_items;
SELECT product_id, stock FROM products;

---modification de la procédure pour création de trigger automatique

CREATE OR REPLACE TRIGGER trg_update_stock
BEFORE INSERT ON order_items
FOR EACH ROW
DECLARE
    v_stock NUMBER;
BEGIN
    SELECT stock INTO v_stock
    FROM products
    WHERE product_id = :NEW.product_id
    FOR UPDATE;

    IF v_stock < :NEW.quantity THEN
        RAISE_APPLICATION_ERROR(-20002, 'Stock insuffisant (trigger)');
    END IF;

    UPDATE products
    SET stock = stock - :NEW.quantity
    WHERE product_id = :NEW.product_id;
END;
/

---Test du trigger
BEGIN 
create_order(1, 2, 5);
END;
/

BEGIN
create_order(1, 2, 5000);
END;
/

---Vue : Total des commandes par client On crée une vue agrégée prête pour reporting.

CREATE OR REPLACE VIEW v_client_totals AS
SELECT
    c.client_id,
    c.name,
    COUNT(DISTINCT o.order_id) AS total_orders,
    NVL(SUM(oi.quantity * p.price), 0) AS total_spent
FROM clients c
LEFT JOIN orders o ON c.client_id = o.client_id
LEFT JOIN order_items oi ON o.order_id = oi.order_id
LEFT JOIN products p ON oi.product_id = p.product_id
GROUP BY c.client_id, c.name;

--test
SELECT* FROM v_client_totals;

-- creation d'index pour optimisation
CREATE INDEX idx_orders_client
ON orders(client_id);

CREATE INDEX idx_order_items_order
ON order_items(order_id);

CREATE INDEX idx_order_items_product
ON order_items(product_id);


SELECT index_name, table_name
FROM user_indexes;


--- Top client(classement)
SELECT 
    name,
    total_spent,
    RANK() OVER (ORDER BY total_spent DESC) AS ranking
FROM v_client_totals;

--- Chiffre d'affaires global
SELECT SUM(total_spent) AS global_revenue
FROM v_client_totals;

--- Produit le plus vendu
SELECT 
    p.product_name,
    SUM(oi.quantity) AS total_quantity
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_quantity DESC;

---Mini Tableau de bord SQL

SELECT 
    (SELECT COUNT(*) FROM clients) AS total_clients,
    (SELECT COUNT(*) FROM orders) AS total_orders,
    (SELECT SUM(quantity) FROM order_items) AS total_products_sold,
    (SELECT SUM(quantity * price)
     FROM order_items oi
     JOIN products p ON oi.product_id = p.product_id) AS total_revenue
FROM dual;


---Package  PL/SQL(regroupement de la logique metier dans un package)

CREATE OR REPLACE PACKAGE order_pkg AS

    PROCEDURE create_order (
        p_client_id   IN NUMBER,
        p_product_id  IN NUMBER,
        p_quantity    IN NUMBER
    );

    PROCEDURE cancel_order (
        p_order_id IN NUMBER
    );

    FUNCTION get_client_total (
        p_client_id IN NUMBER
    ) RETURN NUMBER;

END order_pkg;
/

---Corps du package
CREATE OR REPLACE PACKAGE BODY order_pkg AS

    PROCEDURE create_order (
        p_client_id   IN NUMBER,
        p_product_id  IN NUMBER,
        p_quantity    IN NUMBER
    ) IS
        v_order_id NUMBER;
    BEGIN

        INSERT INTO orders (client_id)
        VALUES (p_client_id)
        RETURNING order_id INTO v_order_id;

        INSERT INTO order_items (order_id, product_id, quantity)
        VALUES (v_order_id, p_product_id, p_quantity);

        COMMIT;
    END;


    PROCEDURE cancel_order (
        p_order_id IN NUMBER
    ) IS
    BEGIN
        -- Rétablir le stock
        FOR rec IN (
            SELECT product_id, quantity
            FROM order_items
            WHERE order_id = p_order_id
        ) LOOP
            UPDATE products
            SET stock = stock + rec.quantity
            WHERE product_id = rec.product_id;
        END LOOP;

        DELETE FROM order_items WHERE order_id = p_order_id;
        DELETE FROM orders WHERE order_id = p_order_id;

        COMMIT;
    END;


    FUNCTION get_client_total (
        p_client_id IN NUMBER
    ) RETURN NUMBER
    IS
        v_total NUMBER;
    BEGIN
        SELECT NVL(SUM(oi.quantity * p.price),0)
        INTO v_total
        FROM orders o
        JOIN order_items oi ON o.order_id = oi.order_id
        JOIN products p ON oi.product_id = p.product_id
        WHERE o.client_id = p_client_id;

        RETURN v_total;
    END;

END order_pkg;
/

---Testing du package

BEGIN 
    order_pkg.create_order(1,1,1);
END;
/

---Test annulation

BEGIN
    order_pkg.cancel_order(1);
END;
/

---Audit automatique
--Création de table historique

CREATE TABLE orders_audit (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_id NUMBER,
    action_type VARCHAR2(30),
    action_date DATE DEFAULT SYSDATE
);

--Création trigger audit

CREATE OR REPLACE TRIGGER trg_orders_audit
AFTER INSERT OR DELETE ON orders
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO orders_audit(order_id, action_type)
        VALUES (:NEW.order_id, 'INSERT');
    ELSIF DELETING THEN
        INSERT INTO orders_audit(order_id, action_type)
        VALUES (:OLD.order_id, 'DELETE');
    END IF;
END;
/

---Analyse performance

EXPLAIN PLAN FOR
SELECT * FROM v_client_totals;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

---Simulation charge

BEGIN
    FOR i IN 1..100 LOOP
        order_pkg.create_order(1, 1, 1);
    END LOOP;
END;
/

SELECT COUNT(*) FROM orders;







